export const LOAD_BLOGS_DATA = "LOAD_BLOGS_DATA";
export const SORT_BY_UPDATE = "SORT_BY_UPDATE";
export const SORT_BY_LAST_UPDATE = "SORT_BY_LAST_UPDATE";
export const ADD_READING_HISTORY = "ADD_READING_HISTORY";
export const ADD_BLOG = "ADD_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const UPDATE_POST = "UPDATE_POST";
