export const LOAD_BLOGS_DATA = "LOAD_BLOGS_DATA";
export const SORT_BY_UPDATE = "SORT_BY_UPDATE";
export const SORT_BY_LAST_UPDATE = "SORT_BY_LAST_UPDATE";
export const ADD_READING_HISTORY = "ADD_READING_HISTORY";
